'/':
  controller: Pages
  action: default

'/liste_des_utilisateurs':
  controller: Users
  action: default

'/ajouter_un_utilisateur':
  controller: Users
  action: add

'/connexion':
  controller: Users
  action: login

'/mot_de_passe_oublie':
  controller: Users
  action: forgetPassword